// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dlocator

import (
	"github.com/digiexpress/dlocator/internal/app/dlocator/courier"
	"github.com/digiexpress/dlocator/internal/pkg/api"
	"github.com/digiexpress/dlocator/internal/pkg/config"
	"github.com/digiexpress/dlocator/internal/pkg/service"
)

// Injectors from wire.go:

func CreateApp() (*App, error) {
	appConfig, err := config.NewAppConfig()
	if err != nil {
		return nil, err
	}
	cacheServiceImpl, err := service.NewCacheService(appConfig)
	if err != nil {
		return nil, err
	}
	cacheRepositoryImpl := courier.NewCacheRepository(cacheServiceImpl)
	commandHandler := courier.NewCourierCommandHandler(cacheRepositoryImpl)
	queryHandler := courier.NewCourierQueryHandler(cacheRepositoryImpl)
	courierLocatorServer := InjectCourierLocatorServer(commandHandler, queryHandler)
	dLocatorGrpcServer, err := api.NewDLocatorGrpcServer(courierLocatorServer, appConfig)
	if err != nil {
		return nil, err
	}
	app := NewApp(appConfig, dLocatorGrpcServer)
	return app, nil
}
