version: '3.9'
services:
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=1234
    volumes:
      - redis_storage:/bitnami/redis/data

  dlocator:
    image: dlocator
    network_mode: host
    depends_on:
      - redis

volumes:
  redis_storage: { }
